-- MySQL Script generated by MySQL Workbench
-- Mon Aug 22 11:23:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Info` (
  `idNome` INT NOT NULL AUTO_INCREMENT,
  `sobrenome` VARCHAR(60) NOT NULL,
  `genero` VARCHAR(9) NOT NULL,
  `altura` DECIMAL(3) NOT NULL,
  `peso` DECIMAL(3) NOT NULL,
  `atestado` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idNome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `nome` VARCHAR(40) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `Info_idNome` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Matricula_Info_idx` (`Info_idNome` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Info`
    FOREIGN KEY (`Info_idNome`)
    REFERENCES `mydb`.`Info` (`idNome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
